# -*- coding: utf-8 -*-
"""Trader Behavior Analysis Based on Market Sentiment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NpTNkT7xGSQadNEmtHMIlMrgrTjJC1jj

# Trader Behavior Analysis Based on Market Sentiment

## Objective

This project analyzes the relationship between cryptocurrency trader behavior and market sentiment using historical trading data and the Bitcoin Fear & Greed Index.

## Datasets Used

1. Historical Hyperliquid Trader Data
2. Bitcoin Fear & Greed Index

## Methodology

- Data Cleaning
- Feature Engineering
- Dataset Merging
- Exploratory Data Analysis
- Trader Performance Analysis
- Statistical Testing

## Tools

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn
- SciPy
"""

# LIBRARIES
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy.stats import kruskal

sns.set_style("whitegrid")
pd.set_option("display.max_columns", None)

# DATASETS
trades = pd.read_csv("historical_data.csv")
sentiment = pd.read_csv("fear_greed_index - fear_greed_index.csv")

print("Trades Dataset Shape:", trades.shape)
print("Sentiment Dataset Shape:", sentiment.shape)

# DATA INFORMATION
print("Trades Dataset Info")
trades.info()

print("\nMissing Values")
print(trades.isnull().sum())

print("\nSentiment Dataset Info")
sentiment.info()

print("\nMissing Values")
print(sentiment.isnull().sum())

# DATA CLEANING
trades["Timestamp IST"] = pd.to_datetime(
    trades["Timestamp IST"],
    dayfirst=True
)

trades["Date"] = trades["Timestamp IST"].dt.date

sentiment["date"] = pd.to_datetime(sentiment["date"])

sentiment["Date"] = sentiment["date"].dt.date
trades.drop_duplicates(inplace=True)

print("Trades Shape After Cleaning:", trades.shape)

# FEATURE ENGINEERING
# Trade considered successful if PnL > 0

trades["Win"] = trades["Closed PnL"] > 0
trades[["Closed PnL", "Win"]].head()

# MERGE DATASETS
merged = pd.merge(
    trades,
    sentiment[["Date", "classification", "value"]],
    on="Date",
    how="left"
)

print("Merged Dataset Shape:", merged.shape)

display(merged.head())

# SENTIMENT DISTRIBUTION
plt.figure(figsize=(8,5))

merged["classification"].value_counts().plot(
    kind="bar"
)

plt.title("Distribution of Market Sentiment")
plt.xlabel("Sentiment")
plt.ylabel("Count")

plt.show()

# PNL VS SENTIMENT
plt.figure(figsize=(10,5))

sns.barplot(
    data=merged,
    x="classification",
    y="Closed PnL",
    estimator=np.mean
)

plt.title("Average Profit/Loss by Sentiment")
plt.xlabel("Market Sentiment")
plt.ylabel("Average Closed PnL")

plt.show()

# WIN RATE ANALYSIS
win_rate = (
    merged.groupby("classification")["Win"]
    .mean()
    * 100
)

win_rate.sort_values().plot(
    kind="bar",
    figsize=(10,5)
)

plt.title("Win Rate by Market Sentiment")
plt.ylabel("Win Rate (%)")
plt.show()
print(win_rate)
# TRADE COUNT ANALYSIS

trade_count = merged["classification"].value_counts()
trade_count.plot(
    kind="bar",
    figsize=(10,5)
)

plt.title("Number of Trades by Sentiment")
plt.ylabel("Trade Count")
plt.show()
trade_count = merged["classification"].value_counts()
trade_count.plot(
    kind="bar",
    figsize=(10,5)
)

plt.title("Number of Trades by Sentiment")
plt.ylabel("Trade Count")
plt.show()

# SENTIMENT SCORING
score_map = {
    "Extreme Fear": 0,
    "Fear": 1,
    "Neutral": 2,
    "Greed": 3,
    "Extreme Greed": 4
}
merged["Sentiment Score"] = merged[
    "classification"
].map(score_map)

display(
    merged[
        ["classification", "Sentiment Score"]
    ].head()
)

correlation_matrix = merged[
    [
        "Closed PnL",
        "Size USD",
        "Fee",
        "Sentiment Score"
    ]
].corr()

plt.figure(figsize=(8,6))

sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Matrix")
plt.show()

# TRADER PERFORMANCE
trader_performance = merged.groupby("Account").agg(
    Total_PnL=("Closed PnL", "sum"),
    Average_PnL=("Closed PnL", "mean"),
    Win_Rate=("Win", "mean"),
    Total_Trades=("Closed PnL", "count")
)

trader_performance["Win_Rate"] *= 100

trader_performance = trader_performance.sort_values(
    "Total_PnL",
    ascending=False
)
display(trader_performance.head(10))

# TOP 10 TRADERS
top10 = trader_performance.head(10)
plt.figure(figsize=(12,5))
sns.barplot(
    x=top10.index,
    y=top10["Total_PnL"]
)

plt.title("Top 10 Traders by Total Profit")
plt.xticks(rotation=90)
plt.show()

# KRUSKAL-WALLIS TEST
groups = []
for sentiment_name in merged[
    "classification"
].dropna().unique():
    groups.append(
        merged[
            merged["classification"] == sentiment_name
        ]["Closed PnL"]
    )

statistic, p_value = kruskal(*groups)
print("Statistic :", statistic)
print("P-Value   :", p_value)
if p_value < 0.05:
    print(
        "\nResult: Market sentiment has a statistically significant impact on trader profitability."
    )
else:
    print(
        "\nResult: No statistically significant relationship detected."
    )


trader_performance.to_csv(
    "Trader_Performance_Report.csv"
)

print("Report Saved Successfully")

"""# Conclusion

This analysis explored the relationship between trader behavior and market sentiment using Hyperliquid trading data and the Bitcoin Fear & Greed Index.

## Key Findings

- Trading activity varied across different sentiment regimes.
- Profitability showed noticeable differences between Fear and Greed periods.
- Position sizing behavior changed with market sentiment.
- Win rates were not consistent across sentiment categories.
- Statistical testing was performed to evaluate whether sentiment significantly impacts profitability.

## Business Implications

Understanding trader behavior under varying market sentiment conditions can help identify risk patterns, optimize trading strategies, and improve portfolio management decisions.
"""